// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using thehaguetech_community_portal.Models;

namespace thehaguetech_community_portal.Migrations
{
    [DbContext(typeof(PortalContext))]
    [Migration("20191126103102_PortalMigrations")]
    partial class PortalMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("thehaguetech_community_portal.Models.Event", b =>
                {
                    b.Property<int>("eventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("creatorprofileID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("picture")
                        .HasColumnType("TEXT");

                    b.Property<int?>("roomID")
                        .HasColumnType("INTEGER");

                    b.HasKey("eventID");

                    b.HasIndex("creatorprofileID");

                    b.HasIndex("roomID");

                    b.ToTable("events");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.EventAttend", b =>
                {
                    b.Property<int>("eventAttendID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("eventFKIDeventID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("profileFKIDprofileID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("registrationDate")
                        .HasColumnType("Date");

                    b.HasKey("eventAttendID");

                    b.HasIndex("eventFKIDeventID");

                    b.HasIndex("profileFKIDprofileID");

                    b.ToTable("eventAttends");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.Profile", b =>
                {
                    b.Property<int>("profileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("expertise")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("memberSince")
                        .HasColumnType("INTEGER");

                    b.Property<string>("picture")
                        .HasColumnType("TEXT");

                    b.HasKey("profileID");

                    b.ToTable("profiles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Profile");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.ProfileRelationship", b =>
                {
                    b.Property<int>("ProfileRelationShipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("connectionDate")
                        .HasColumnType("Date");

                    b.Property<int>("profileConnectionFKIDprofileID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("profileFKIDprofileID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileRelationShipID");

                    b.HasIndex("profileConnectionFKIDprofileID");

                    b.HasIndex("profileFKIDprofileID");

                    b.ToTable("profileRelationships");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.Room", b =>
                {
                    b.Property<int>("roomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("equipment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("number")
                        .HasColumnType("INTEGER");

                    b.HasKey("roomID");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.RoomBooking", b =>
                {
                    b.Property<int>("roomBookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("profileFKIDprofileID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("registrationDate")
                        .HasColumnType("Date");

                    b.Property<int>("roomFKIDroomID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("timeEnd")
                        .HasColumnType("Date");

                    b.Property<DateTime>("timeStart")
                        .HasColumnType("Date");

                    b.HasKey("roomBookingID");

                    b.HasIndex("profileFKIDprofileID");

                    b.HasIndex("roomFKIDroomID");

                    b.ToTable("roombookings");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.SocialLink", b =>
                {
                    b.Property<int>("linkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("profileFKIDprofileID")
                        .HasColumnType("INTEGER");

                    b.HasKey("linkID");

                    b.HasIndex("profileFKIDprofileID");

                    b.ToTable("socialLinks");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.Comapny", b =>
                {
                    b.HasBaseType("thehaguetech_community_portal.Models.Profile");

                    b.Property<string>("contactPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Comapny");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.Event", b =>
                {
                    b.HasOne("thehaguetech_community_portal.Models.Profile", "creator")
                        .WithMany()
                        .HasForeignKey("creatorprofileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("thehaguetech_community_portal.Models.Room", "room")
                        .WithMany()
                        .HasForeignKey("roomID");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.EventAttend", b =>
                {
                    b.HasOne("thehaguetech_community_portal.Models.Event", "eventFKID")
                        .WithMany()
                        .HasForeignKey("eventFKIDeventID");

                    b.HasOne("thehaguetech_community_portal.Models.Profile", "profileFKID")
                        .WithMany()
                        .HasForeignKey("profileFKIDprofileID");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.ProfileRelationship", b =>
                {
                    b.HasOne("thehaguetech_community_portal.Models.Profile", "profileConnectionFKID")
                        .WithMany()
                        .HasForeignKey("profileConnectionFKIDprofileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("thehaguetech_community_portal.Models.Profile", "profileFKID")
                        .WithMany()
                        .HasForeignKey("profileFKIDprofileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.RoomBooking", b =>
                {
                    b.HasOne("thehaguetech_community_portal.Models.Profile", "profileFKID")
                        .WithMany()
                        .HasForeignKey("profileFKIDprofileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("thehaguetech_community_portal.Models.Room", "roomFKID")
                        .WithMany()
                        .HasForeignKey("roomFKIDroomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.SocialLink", b =>
                {
                    b.HasOne("thehaguetech_community_portal.Models.Profile", "profileFKID")
                        .WithMany()
                        .HasForeignKey("profileFKIDprofileID");
                });
#pragma warning restore 612, 618
        }
    }
}
