// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using thehaguetech_community_portal.Models;

namespace thehaguetech_community_portal.Migrations
{
    [DbContext(typeof(PortalContext))]
    [Migration("20191125113217_ModelChanges")]
    partial class ModelChanges
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("thehaguetech_community_portal.Models.Event", b =>
                {
                    b.Property<int>("eventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("eventID");

                    b.ToTable("events");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.Profile", b =>
                {
                    b.Property<int>("profileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("expertise")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("memberSince")
                        .HasColumnType("INTEGER");

                    b.Property<string>("picture")
                        .HasColumnType("TEXT");

                    b.Property<int?>("profileID1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("roomID")
                        .HasColumnType("INTEGER");

                    b.HasKey("profileID");

                    b.HasIndex("profileID1");

                    b.HasIndex("roomID");

                    b.ToTable("profiles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Profile");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.Room", b =>
                {
                    b.Property<int>("roomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("roomID");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.SocialLink", b =>
                {
                    b.Property<int>("socialLinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("profileID")
                        .HasColumnType("INTEGER");

                    b.HasKey("socialLinkID");

                    b.HasIndex("profileID");

                    b.ToTable("socialLinks");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.Comapny", b =>
                {
                    b.HasBaseType("thehaguetech_community_portal.Models.Profile");

                    b.Property<int>("companyID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("contactPerson")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Comapny");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.Profile", b =>
                {
                    b.HasOne("thehaguetech_community_portal.Models.Profile", null)
                        .WithMany("connections")
                        .HasForeignKey("profileID1");

                    b.HasOne("thehaguetech_community_portal.Models.Room", null)
                        .WithMany("booker")
                        .HasForeignKey("roomID");
                });

            modelBuilder.Entity("thehaguetech_community_portal.Models.SocialLink", b =>
                {
                    b.HasOne("thehaguetech_community_portal.Models.Profile", null)
                        .WithMany("socialLinks")
                        .HasForeignKey("profileID");
                });
#pragma warning restore 612, 618
        }
    }
}
