// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using thehaguetech_community_portal.Models;

namespace thehaguetech_community_portal.Migrations
{
    [DbContext(typeof(PortalContext))]
    partial class PortalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1");

            modelBuilder.Entity("thehaguetech_community_portal.Models.Profile", b =>
                {
                    b.Property<int>("profileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("expertise")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("memberSince")
                        .HasColumnType("INTEGER");

                    b.Property<string>("picture")
                        .HasColumnType("TEXT");

                    b.Property<string>("socialLinks")
                        .HasColumnType("TEXT");

                    b.HasKey("profileID");

                    b.ToTable("profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
